#:kivy 2.0.0

<SwirlWorld>:
    canvas:
        Rectangle:
            pos: self.center_x - 400, self.center_y - 4
            size: 800, 8

    PendulumCart:
        center: self.parent.center

    PendulumBob:
        center: self.parent.center

<PendulumBob>:
    size: 50, 50
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<PendulumCart>:
    size: 100, 50
    canvas:
        Rectangle:
            pos: self.center_x - 50, 400
            size: self.size
